{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "94cac3f6",
   "metadata": {},
   "source": [
    "#### HOW TO LOAD SQL\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "154bb422",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandasql in c:\\users\\hp\\anaconda3\\lib\\site-packages (0.7.3)\n",
      "Requirement already satisfied: sqlalchemy in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pandasql) (2.0.4)\n",
      "Requirement already satisfied: pandas in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pandasql) (1.4.4)\n",
      "Requirement already satisfied: numpy in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pandasql) (1.21.5)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pandas->pandasql) (2022.1)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pandas->pandasql) (2.8.2)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from sqlalchemy->pandasql) (1.1.1)\n",
      "Requirement already satisfied: typing-extensions>=4.2.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from sqlalchemy->pandasql) (4.3.0)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.1->pandas->pandasql) (1.16.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install -U pandasql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "dbcbc6c6",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: sqlalchemy in c:\\users\\hp\\anaconda3\\lib\\site-packages (2.0.4)\n",
      "Requirement already satisfied: typing-extensions>=4.2.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from sqlalchemy) (4.3.0)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from sqlalchemy) (1.1.1)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install sqlalchemy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "84f6a1bc",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: ipython-sql in c:\\users\\hp\\anaconda3\\lib\\site-packages (0.5.0)\n",
      "Requirement already satisfied: ipython in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython-sql) (7.31.1)\n",
      "Requirement already satisfied: sqlparse in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython-sql) (0.4.3)\n",
      "Requirement already satisfied: prettytable in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython-sql) (3.6.0)\n",
      "Requirement already satisfied: ipython-genutils in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython-sql) (0.2.0)\n",
      "Requirement already satisfied: six in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython-sql) (1.16.0)\n",
      "Requirement already satisfied: sqlalchemy>=2.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython-sql) (2.0.4)\n",
      "Requirement already satisfied: typing-extensions>=4.2.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.3.0)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from sqlalchemy>=2.0->ipython-sql) (1.1.1)\n",
      "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (3.0.20)\n",
      "Requirement already satisfied: pygments in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (2.11.2)\n",
      "Requirement already satisfied: pickleshare in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.7.5)\n",
      "Requirement already satisfied: decorator in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (5.1.1)\n",
      "Requirement already satisfied: traitlets>=4.2 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (5.1.1)\n",
      "Requirement already satisfied: colorama in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.4.5)\n",
      "Requirement already satisfied: jedi>=0.16 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.18.1)\n",
      "Requirement already satisfied: setuptools>=18.5 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (63.4.1)\n",
      "Requirement already satisfied: matplotlib-inline in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.1.6)\n",
      "Requirement already satisfied: backcall in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.2.0)\n",
      "Requirement already satisfied: wcwidth in c:\\users\\hp\\anaconda3\\lib\\site-packages (from prettytable->ipython-sql) (0.2.5)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install ipython-sql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "f125f1c7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting package metadata (current_repodata.json): ...working... done\n",
      "Solving environment: ...working... done\n",
      "\n",
      "# All requested packages already installed.\n",
      "\n",
      "\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "conda install sqlite"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "c4dfd53c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pyhive[presto] in c:\\users\\hp\\anaconda3\\lib\\site-packages (0.6.5)Note: you may need to restart the kernel to use updated packages.\n",
      "\n",
      "Requirement already satisfied: python-dateutil in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pyhive[presto]) (2.8.2)\n",
      "Requirement already satisfied: future in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pyhive[presto]) (0.18.2)\n",
      "Requirement already satisfied: requests>=1.0.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pyhive[presto]) (2.28.1)\n",
      "Requirement already satisfied: charset-normalizer<3,>=2 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from requests>=1.0.0->pyhive[presto]) (2.0.4)\n",
      "Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from requests>=1.0.0->pyhive[presto]) (1.26.11)\n",
      "Requirement already satisfied: idna<4,>=2.5 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from requests>=1.0.0->pyhive[presto]) (3.3)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from requests>=1.0.0->pyhive[presto]) (2022.12.7)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from python-dateutil->pyhive[presto]) (1.16.0)\n"
     ]
    }
   ],
   "source": [
    "pip install pyhive[presto]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "8eab8e82",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The sql extension is already loaded. To reload it, use:\n",
      "  %reload_ext sql\n"
     ]
    }
   ],
   "source": [
    "# Loading external sql\n",
    "# This will load the SQL module in the notebook. Now, with the use of %sql magic, you can use SQL queries directly\n",
    "# in Jupyter Notebook.\n",
    "%load_ext sql"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a98e3ea5",
   "metadata": {},
   "source": [
    "# CREATE SQL DATABASE"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "d5e02a61",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 45, in __init__\n",
      "    engine = sqlalchemy.create_engine(\n",
      "  File \"<string>\", line 2, in create_engine\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\deprecations.py\", line 309, in warned\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 576, in create_engine\n",
      "    (cargs, cparams) = dialect.create_connect_args(u)\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sqlalchemy\\dialects\\sqlite\\pysqlite.py\", line 551, in create_connect_args\n",
      "    raise exc.ArgumentError(\n",
      "sqlalchemy.exc.ArgumentError: Invalid SQLite URL: sqlite://contactInfo.db3\n",
      "Valid SQLite URL forms are:\n",
      " sqlite:///:memory: (or, sqlite://)\n",
      " sqlite:///relative/path/to/file.db\n",
      " sqlite:////absolute/path/to/file.db\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 70, in set\n",
      "    cls.current = existing or Connection(descriptor, connect_args, creator)\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 45, in __init__\n",
      "    engine = sqlalchemy.create_engine(\n",
      "  File \"<string>\", line 2, in create_engine\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\deprecations.py\", line 309, in warned\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 576, in create_engine\n",
      "    (cargs, cparams) = dialect.create_connect_args(u)\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sqlalchemy\\dialects\\sqlite\\pysqlite.py\", line 551, in create_connect_args\n",
      "    raise exc.ArgumentError(\n",
      "sqlalchemy.exc.ArgumentError: Invalid SQLite URL: sqlite://contactInfo.db3\n",
      "Valid SQLite URL forms are:\n",
      " sqlite:///:memory: (or, sqlite://)\n",
      " sqlite:///relative/path/to/file.db\n",
      " sqlite:////absolute/path/to/file.db\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys([])\n"
     ]
    }
   ],
   "source": [
    "%sql sqlite://contactInfo.db3"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a5e1ce5e",
   "metadata": {},
   "source": [
    "# CREATE A TABLE"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "8817d67e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 203, in execute\n",
      "    conn.internal_connection.rollback()\n",
      "AttributeError: 'Connection' object has no attribute 'rollback'\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys(['sqlite://'])\n"
     ]
    }
   ],
   "source": [
    "%%sql sqlite://\n",
    "CREATE TABLE contactInfo(\n",
    "    FirstName VARCHAR(50) NOT NULL,\n",
    "    LastName VARCHAR(50) NOT NULL,  \n",
    "    USERID int  NOT NULL UNIQUE, \n",
    "    PRIMARY KEY (USERID)\n",
    ");"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "0e60ad60",
   "metadata": {},
   "source": [
    "# ADD DATA TO THE TABLE"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "db2b838f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 203, in execute\n",
      "    conn.internal_connection.rollback()\n",
      "AttributeError: 'Connection' object has no attribute 'rollback'\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys(['sqlite://'])\n"
     ]
    }
   ],
   "source": [
    "%%sql sqlite://\n",
    "INSERT INTO contactInfo VALUES ('Akinroye', 'Muideen', 8134324983);\n",
    "INSERT INTO contactInfo VALUES ('Akinroye', 'Azeez', 7063684912);\n",
    "INSERT INTO contactInfo VALUES ('Olanipekun', 'Abigeal', 8063362208);\n",
    "INSERT INTO contactInfo VALUES ('Abiola', 'Olayanju', 7056434242);\n",
    "INSERT INTO contactInfo VALUES ('Emannuel', 'Clement', 9078474743);"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "36571ee9",
   "metadata": {},
   "source": [
    "# WRITE THE FIRST QUERY"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "cfe16f75",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * sqlite://\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 203, in execute\n",
      "    conn.internal_connection.rollback()\n",
      "AttributeError: 'Connection' object has no attribute 'rollback'\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys(['sqlite://'])\n"
     ]
    }
   ],
   "source": [
    "sql_query = %sql SELECT * from contactInfo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "430dd30d",
   "metadata": {},
   "outputs": [],
   "source": [
    "sql_query"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "69a46939",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * sqlite://\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 203, in execute\n",
      "    conn.internal_connection.rollback()\n",
      "AttributeError: 'Connection' object has no attribute 'rollback'\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys(['sqlite://'])\n"
     ]
    }
   ],
   "source": [
    "sql_query = %sql SELECT FirstName, LastName from contactInfo"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "c1d9e8b9",
   "metadata": {},
   "outputs": [],
   "source": [
    "sql_query"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "0b24d837",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 203, in execute\n",
      "    conn.internal_connection.rollback()\n",
      "AttributeError: 'Connection' object has no attribute 'rollback'\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys(['sqlite://'])\n"
     ]
    }
   ],
   "source": [
    "%%sql sqlite://\n",
    "CREATE TABLE contact(\n",
    "    Phone_Number int(50) NOT NULL,\n",
    "    Address VARCHAR(50) NOT NULL, \n",
    "    Gender VARCHAR(50) NOT NULL,\n",
    "    EMPLID int  NOT NULL UNIQUE, \n",
    "    PRIMARY KEY (EMPLID)\n",
    ");"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "3bcca7d8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 203, in execute\n",
      "    conn.internal_connection.rollback()\n",
      "AttributeError: 'Connection' object has no attribute 'rollback'\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys(['sqlite://'])\n"
     ]
    }
   ],
   "source": [
    "%%sql sqlite://\n",
    "INSERT INTO contact VALUES ('8054098000', 'Brooklyn New York USA', 'F', 2);\n",
    "INSERT INTO contact VALUES ('1479961014', 'Grenelle Paris France', 'M', 3);\n",
    "INSERT INTO contact VALUES ('2011503193', 'Geuzenveld Amsterdam Netherlands', 'F', 4);\n",
    "INSERT INTO contact VALUES ('6723482456', 'Yishun Singapore', 'M', 7);\n",
    "INSERT INTO contact VALUES ('3577990724', 'Koto City, Tokyo, Japan', 'M', 8) \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "5ff35f28",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * sqlite://\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 203, in execute\n",
      "    conn.internal_connection.rollback()\n",
      "AttributeError: 'Connection' object has no attribute 'rollback'\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys(['sqlite://'])\n"
     ]
    }
   ],
   "source": [
    "sql_query = %sql SELECT * from contact"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "b743b63a",
   "metadata": {},
   "outputs": [],
   "source": [
    "sql_query"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "831da2e6",
   "metadata": {},
   "source": [
    "# CRUD OPERATION IN SQL\n",
    "# CREATE\n",
    "# READ\n",
    "# UPDATE\n",
    "# DELETE"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "91e82376",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandasql in c:\\users\\hp\\anaconda3\\lib\\site-packages (0.7.3)\n",
      "Requirement already satisfied: sqlalchemy in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pandasql) (2.0.4)\n",
      "Requirement already satisfied: numpy in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pandasql) (1.21.5)\n",
      "Requirement already satisfied: pandas in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pandasql) (1.4.4)\n",
      "Requirement already satisfied: python-dateutil>=2.8.1 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pandas->pandasql) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from pandas->pandasql) (2022.1)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from sqlalchemy->pandasql) (1.1.1)\n",
      "Requirement already satisfied: typing-extensions>=4.2.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from sqlalchemy->pandasql) (4.3.0)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.1->pandas->pandasql) (1.16.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install -U pandasql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "7694dc32",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: ipython-sql in c:\\users\\hp\\anaconda3\\lib\\site-packages (0.5.0)\n",
      "Requirement already satisfied: ipython in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython-sql) (7.31.1)\n",
      "Requirement already satisfied: sqlparse in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython-sql) (0.4.3)\n",
      "Requirement already satisfied: prettytable in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython-sql) (3.6.0)\n",
      "Requirement already satisfied: ipython-genutils in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython-sql) (0.2.0)\n",
      "Requirement already satisfied: six in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython-sql) (1.16.0)\n",
      "Requirement already satisfied: sqlalchemy>=2.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython-sql) (2.0.4)\n",
      "Requirement already satisfied: typing-extensions>=4.2.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from sqlalchemy>=2.0->ipython-sql) (4.3.0)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from sqlalchemy>=2.0->ipython-sql) (1.1.1)\n",
      "Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (3.0.20)\n",
      "Requirement already satisfied: backcall in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.2.0)\n",
      "Requirement already satisfied: matplotlib-inline in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.1.6)\n",
      "Requirement already satisfied: jedi>=0.16 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.18.1)\n",
      "Requirement already satisfied: decorator in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (5.1.1)\n",
      "Requirement already satisfied: pygments in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (2.11.2)\n",
      "Requirement already satisfied: colorama in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.4.5)\n",
      "Requirement already satisfied: setuptools>=18.5 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (63.4.1)\n",
      "Requirement already satisfied: traitlets>=4.2 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (5.1.1)\n",
      "Requirement already satisfied: pickleshare in c:\\users\\hp\\anaconda3\\lib\\site-packages (from ipython->ipython-sql) (0.7.5)\n",
      "Requirement already satisfied: wcwidth in c:\\users\\hp\\anaconda3\\lib\\site-packages (from prettytable->ipython-sql) (0.2.5)\n",
      "Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from jedi>=0.16->ipython->ipython-sql) (0.8.3)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install ipython-sql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "e0b40dc9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "The sql extension is already loaded. To reload it, use:\n",
      "  %reload_ext sql\n"
     ]
    }
   ],
   "source": [
    "%load_ext sql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "4a7b7ab7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 45, in __init__\n",
      "    engine = sqlalchemy.create_engine(\n",
      "  File \"<string>\", line 2, in create_engine\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\deprecations.py\", line 309, in warned\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 576, in create_engine\n",
      "    (cargs, cparams) = dialect.create_connect_args(u)\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sqlalchemy\\dialects\\sqlite\\pysqlite.py\", line 551, in create_connect_args\n",
      "    raise exc.ArgumentError(\n",
      "sqlalchemy.exc.ArgumentError: Invalid SQLite URL: sqlite://Mydata.db3\n",
      "Valid SQLite URL forms are:\n",
      " sqlite:///:memory: (or, sqlite://)\n",
      " sqlite:///relative/path/to/file.db\n",
      " sqlite:////absolute/path/to/file.db\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys(['sqlite://'])\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 196, in execute\n",
      "    conn = sql.connection.Connection.set(\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 70, in set\n",
      "    cls.current = existing or Connection(descriptor, connect_args, creator)\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\connection.py\", line 45, in __init__\n",
      "    engine = sqlalchemy.create_engine(\n",
      "  File \"<string>\", line 2, in create_engine\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sqlalchemy\\util\\deprecations.py\", line 309, in warned\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 576, in create_engine\n",
      "    (cargs, cparams) = dialect.create_connect_args(u)\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sqlalchemy\\dialects\\sqlite\\pysqlite.py\", line 551, in create_connect_args\n",
      "    raise exc.ArgumentError(\n",
      "sqlalchemy.exc.ArgumentError: Invalid SQLite URL: sqlite://Mydata.db3\n",
      "Valid SQLite URL forms are:\n",
      " sqlite:///:memory: (or, sqlite://)\n",
      " sqlite:///relative/path/to/file.db\n",
      " sqlite:////absolute/path/to/file.db\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys(['sqlite://'])\n"
     ]
    }
   ],
   "source": [
    "%sql sqlite://Mydata.db3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "9e023f1c",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 203, in execute\n",
      "    conn.internal_connection.rollback()\n",
      "AttributeError: 'Connection' object has no attribute 'rollback'\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys(['sqlite://'])\n"
     ]
    }
   ],
   "source": [
    "%%sql sqlite://\n",
    "INSERT INTO contact VALUES ('8054098000', 'Brooklyn New York USA', 'F', 2);\n",
    "INSERT INTO contact VALUES ('1479961014', 'Grenelle Paris France', 'M', 3);\n",
    "INSERT INTO contact VALUES ('2011503193', 'Geuzenveld Amsterdam Netherlands', 'F', 4);\n",
    "INSERT INTO contact VALUES ('6723482456', 'Yishun Singapore', 'M', 7);\n",
    "INSERT INTO contact VALUES ('3577990724', 'Koto City, Tokyo, Japan', 'M', 8) \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "f28fcbbf",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: sqlalchemy in c:\\users\\hp\\anaconda3\\lib\\site-packages (2.0.4)\n",
      "Requirement already satisfied: greenlet!=0.4.17 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from sqlalchemy) (1.1.1)\n",
      "Requirement already satisfied: typing-extensions>=4.2.0 in c:\\users\\hp\\anaconda3\\lib\\site-packages (from sqlalchemy) (4.3.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install sqlalchemy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "id": "a4f1f8e5",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\HP\\anaconda3\\lib\\site-packages\\sql\\magic.py\", line 203, in execute\n",
      "    conn.internal_connection.rollback()\n",
      "AttributeError: 'Connection' object has no attribute 'rollback'\n",
      "\n",
      "Connection info needed in SQLAlchemy format, example:\n",
      "               postgresql://username:password@hostname/dbname\n",
      "               or an existing connection: dict_keys(['sqlite://'])\n"
     ]
    }
   ],
   "source": [
    "%%sql sqlite://\n",
    "CREATE TABLE contactInfo(\n",
    "    FirstName VARCHAR(50) NOT NULL,\n",
    "    LastName VARCHAR(50) NOT NULL,  \n",
    "    USERID int  NOT NULL UNIQUE, \n",
    "    PRIMARY KEY (USERID)\n",
    ");"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f54ea6b1",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "df1bc0b2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
